# Custom Partitioning Configuration
# Converted from kickstart partitioning commands

[[partitions]]
name = "biosboot"
type = "partition"
fstype = "biosboot"
size = 1
mountpoint = ""

[[partitions]]
name = "boot"
type = "partition"
fstype = "xfs"
size = 750
mountpoint = "/boot"

[[partitions]]
name = "boot_efi"
type = "partition"
fstype = "efi"
size = 750
mountpoint = "/boot/efi"

[[partitions]]
name = "pv_01"
type = "partition"
fstype = "lvmpv"
size = 501375
mountpoint = ""

# Volume Group Configuration
[[volume_groups]]
name = "rhel"
pesize = 4096
physical_volumes = ["pv_01"]

# Logical Volumes
[[logical_volumes]]
name = "root"
vgname = "rhel"
fstype = "xfs"
size = 80000
mountpoint = "/"

[[logical_volumes]]
name = "home"
vgname = "rhel"
fstype = "xfs"
size = 5000
mountpoint = "/home"
grow = true

[[logical_volumes]]
name = "swap"
vgname = "rhel"
fstype = "swap"
size = 8192
mountpoint = ""

[[logical_volumes]]
name = "tmp"
vgname = "rhel"
fstype = "xfs"
size = 15000
mountpoint = "/tmp"
fsoptions = "nodev,nosuid,noexec"

[[logical_volumes]]
name = "var_log"
vgname = "rhel"
fstype = "xfs"
size = 15000
mountpoint = "/var/log"

[[logical_volumes]]
name = "var_log_audit"
vgname = "rhel"
fstype = "xfs"
size = 15000
mountpoint = "/var/log/audit"

[[logical_volumes]]
name = "var"
vgname = "rhel"
fstype = "xfs"
size = 15000
mountpoint = "/var"

[[logical_volumes]]
name = "var_tmp"
vgname = "rhel"
fstype = "xfs"
size = 2048
mountpoint = "/var/tmp"
fsoptions = "nodev,nosuid,noexec"

[[logical_volumes]]
name = "opt"
vgname = "rhel"
fstype = "xfs"
size = 15000
mountpoint = "/opt"
